client:
  baseUrl: https://api.edamam.com/api/recipes/v2
  hostKey: 086cb58392mshbc5d142a5c56b96p1c1fe2jsned95361c2c3a
  hostValue: tasty.p.rapidapi.com

spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://recipes-db.documents.azure.com:443
        key: VloU1pwUMNIJOYezjjlDq74FfFfumvSwUQOImkW8kpwFg4t8FHhLAil1k7L5tgwWjtbuE5OvcxmIACDbTBFmSw==
        database: recipe-test-db
        populate-query-metrics: true
