client:
  baseUrl: https://api.edamam.com/api/recipes/v2
  hostKey: 086cb58392mshbc5d142a5c56b96p1c1fe2jsned95361c2c3a
  hostValue: tasty.p.rapidapi.com

#cosmos:
#  uri: https://cosdb-nosql-js-upskill.documents.azure.com:443/
#  key: tWqkhw2C2R2FtKin6sAz0YktEX7SkWuRcz7c6kezBr7TYnTrt8ApH19NjMlxn1FNM7oPaPXXUOuUACDbXd0E7g==
#  secondaryKey: 7OW1fjM5jfuCtbhErC4iL5eDKB0SGeaUiUbM4FsvpXRUNdgiYuu1odrToRYcAnFTczggvi29LD5KACDbKCZvqA==
#  queryMetricsEnabled: true

spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://cosdb-nosql-js-upskill.documents.azure.com:443/
        key: tWqkhw2C2R2FtKin6sAz0YktEX7SkWuRcz7c6kezBr7TYnTrt8ApH19NjMlxn1FNM7oPaPXXUOuUACDbXd0E7g==
        database: recipedb
        populate-query-metrics: true
